#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys, os

# for development on own machine
try:
	sys.path.extend ([
		'/projekte/python'
	])
except:
	pass
	
from lib_mdsite import cMdWebsite

########################################################################
# flow
########################################################################

n = len (sys.argv)

# TODO commented for development
if n != 2:
	cancelScript ('argument(s) missing, type "mdsite SOURCE_DIR"')

mdDir = sys.argv[n-1]

if os.path.isdir (mdDir) == False:
	cancelScript ('directory ' + mdDir + ' does not exist')
	
mdSite = cMdWebsite (mdDir)
result = mdSite.writeSite ()

sys.exit (0)
